"""Validate the GenAI certification practice questions and render them.

Source of truth: genai-databricks/practice/questions-0N.yaml (format: practice/SCHEMA.md).

Usage:
  python3 scripts/render_questions.py            # validate + write genai-databricks/practice-questions.md
  python3 scripts/render_questions.py --check    # validate + fail if the Markdown is out of date (CI)
  python3 scripts/render_questions.py --json OUT # also write the question bank as JSON (website)
"""

import argparse
import json
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
PRACTICE = ROOT / "genai-databricks" / "practice"
OUT_MD = ROOT / "genai-databricks" / "practice-questions.md"

DOMAINS = {
    1: ("Design Applications", 14),
    2: ("Data Preparation", 14),
    3: ("Application Development", 30),
    4: ("Assembling and Deploying Applications", 22),
    5: ("Governance", 8),
    6: ("Evaluation and Monitoring", 12),
}
REQUIRED = ["id", "domain", "objective", "difficulty", "question", "choices", "answer", "explanation", "refs"]


def load() -> list[dict]:
    questions = []
    for path in sorted(PRACTICE.glob("questions-*.yaml")):
        items = yaml.safe_load(path.read_text()) or []
        for q in items:
            q["_file"] = path.name
        questions.extend(items)
    return questions


def validate(questions: list[dict]) -> list[str]:
    errors, seen = [], set()
    for q in questions:
        where = f"{q.get('_file')}:{q.get('id', '?')}"
        missing = [k for k in REQUIRED if k not in q]
        if missing:
            errors.append(f"{where}: missing {missing}")
            continue
        if q["id"] in seen:
            errors.append(f"{where}: duplicate id")
        seen.add(q["id"])
        if not re.fullmatch(r"D[1-6]-\d{3}", q["id"]) or int(q["id"][1]) != q["domain"]:
            errors.append(f"{where}: id must be D<domain>-NNN and match domain {q['domain']}")
        if q["domain"] not in DOMAINS:
            errors.append(f"{where}: domain must be 1..6")
        answers = q["answer"]
        if not isinstance(answers, list) or not answers:
            errors.append(f"{where}: answer must be a non-empty list")
            continue
        unknown = [a for a in answers if a not in q["choices"]]
        if unknown:
            errors.append(f"{where}: answer {unknown} not among choices {list(q['choices'])}")
        multi = len(answers) > 1
        says_two = bool(re.search(r"\b(which|select|choose) two\b", q["question"], re.I))
        if multi != says_two:
            errors.append(f"{where}: multiple-selection questions must say 'Which TWO' (and only they)")
        if len(answers) > 2:
            errors.append(f"{where}: at most two answers")
        if not q["refs"]:
            errors.append(f"{where}: needs at least one reference")
    return errors


def render_md(questions: list[dict]) -> str:
    out = [
        "# Practice questions — Databricks Generative AI Engineer Associate",
        "",
        "<!-- Generated by scripts/render_questions.py from practice/questions-*.yaml. Do not edit. -->",
        "",
        f"**{len(questions)} original questions**, grouped by exam domain and aligned to the exam guide",
        "(version live since March 18, 2026). Try each question before opening the answer.",
        "On the [course website](https://maiphong0411.github.io/machine-learning-worldclass/genai-databricks/practice-exam/)",
        "the same bank runs as a **timed mock exam** with per-domain scoring.",
        "",
        "| Domain | Exam weight | Questions here |",
        "|---|---|---|",
    ]
    by_domain = {d: [q for q in questions if q["domain"] == d] for d in DOMAINS}
    for d, (name, weight) in DOMAINS.items():
        out.append(f"| [{d}. {name}](#domain-{d}) | {weight}% | {len(by_domain[d])} |")
    for d, (name, weight) in DOMAINS.items():
        out += ["", f'<a id="domain-{d}"></a>', "", f"## Domain {d} — {name} ({weight}%)", ""]
        for q in by_domain[d]:
            kind = " · *choose two*" if len(q["answer"]) > 1 else ""
            out += [f"### {q['id']}{kind}", "", f"*Objective: {q['objective']}*", "", q["question"].strip(), ""]
            out += [f"- **{k}.** {v}" for k, v in q["choices"].items()]
            refs = " · ".join(f"[{i + 1}]({r})" for i, r in enumerate(q["refs"]))
            out += [
                "",
                "<details>",
                f"<summary>Answer: {', '.join(q['answer'])}</summary>",
                "",
                q["explanation"].strip(),
                "",
                f"Docs: {refs}",
                "",
                "</details>",
                "",
            ]
    return "\n".join(out).rstrip() + "\n"


def to_json(questions: list[dict]) -> str:
    keep = ["id", "domain", "objective", "difficulty", "question", "choices", "answer", "explanation", "refs"]
    data = {
        "domains": {str(d): {"name": n, "weight": w} for d, (n, w) in DOMAINS.items()},
        "questions": [{k: q[k] for k in keep} for q in questions],
    }
    return json.dumps(data, ensure_ascii=False)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--json")
    args = ap.parse_args()

    questions = load()
    errors = validate(questions)
    if errors:
        print("Question bank errors:\n  " + "\n  ".join(errors), file=sys.stderr)
        return 1
    md = render_md(questions)
    if args.check:
        if not OUT_MD.exists() or OUT_MD.read_text() != md:
            print(f"{OUT_MD.relative_to(ROOT)} is out of date: run python3 scripts/render_questions.py",
                  file=sys.stderr)
            return 1
    else:
        OUT_MD.write_text(md)
    if args.json:
        Path(args.json).write_text(to_json(questions))
    counts = {d: sum(q["domain"] == d for q in questions) for d in DOMAINS}
    print(f"{len(questions)} questions OK {counts}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
